# Generated by Django 5.1.3 on 2024-11-21 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='ingredients',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='nutritional_info',
        ),
    ]
